services:
  omniplay:
    build:
      context: .
      dockerfile: Dockerfile
    image: omniplay-docker:latest
    container_name: omniplay
    restart: unless-stopped

    network_mode: host

    devices:
      - /dev/dri:/dev/dri

    environment:
      TZ: Asia/Shanghai
      OMNIPLAY_APP_ROOT: /var/lib/omniplay
      OMNIPLAY_CACHE_ROOT: /var/cache/omniplay
      OMNIPLAY_URLS: http://0.0.0.0:45722
      ASPNETCORE_URLS: http://0.0.0.0:45722
      OMNIPLAY_LOCAL_SHARE_ROOTS: /media
      OMNIPLAY_FFMPEG_PATH: /usr/bin/ffmpeg
      OMNIPLAY_FFPROBE_PATH: /usr/bin/ffprobe
      OMNIPLAY_VAAPI_DEVICE: /dev/dri/renderD128
      OMNIPLAY_ENABLE_QSV: "1"
      OMNIPLAY_DOCKER_HOST_NETWORK: "1"

    volumes:
      - ./data:/var/lib/omniplay
      - ./cache:/var/cache/omniplay
      - ./media:/media:ro
